# ---------------------------------------------------------------- PlayerAuthInputFlags / EntityMetadataFlags
"""Bit flags for player authorization inputs and entity metadata."""

# PlayerAuthInputFlags (bit indices within 65-bit bitset)
F_JUMPING = 6
F_SNEAKING = 8
F_SPRINTING = 20
F_START_SPRINTING = 25
F_STOP_SPRINTING = 26
F_START_SNEAKING = 27
F_STOP_SNEAKING = 28
F_START_SWIMMING = 29
F_STOP_SWIMMING = 30
F_START_JUMPING = 31
F_START_GLIDING = 32
F_STOP_GLIDING = 33
F_PERFORM_ITEM_INTERACTION = 34
F_PERFORM_BLOCK_ACTIONS = 35
F_PERFORM_ITEM_STACK_REQUEST = 36
F_HANDLED_TELEPORT = 37
F_MISSED_SWING = 39
F_START_CRAWLING = 40
F_STOP_CRAWLING = 41
F_START_FLYING = 42
F_STOP_FLYING = 43

# PlayerBlockAction / PlayerAction types carried by PlayerAuthInput block actions
BA_START_BREAK = 0
BA_ABORT_BREAK = 1
BA_STOP_BREAK = 2
BA_CRACK_BREAK = 18
BA_PREDICT_DESTROY_BLOCK = 26
BA_CONTINUE_DESTROY_BLOCK = 27

# EntityMetadataFlags
MF_SNEAKING = 1
MF_SPRINTING = 3
MF_NAMETAG = 14
MF_ALWAYS_NAMETAG = 15
MF_GLIDING = 32
MF_BREATHING = 35
MF_COLLISION = 48
MF_GRAVITY = 49
MF_SWIMMING = 57
MF_CRAWLING = 114  # >= 64 lives in FLAGS2

# Every PlayerAuthInputFlags bit name for diagnostics and logging
INPUT_FLAG_NAMES = {
    0: "ASCEND",
    1: "DESCEND",
    2: "NORTH_JUMP",
    3: "JUMP_DOWN",
    4: "SPRINT_DOWN",
    5: "CHANGE_HEIGHT",
    6: "JUMPING",
    7: "AUTO_JUMPING_IN_WATER",
    8: "SNEAKING",
    9: "SNEAK_DOWN",
    10: "UP",
    11: "DOWN",
    12: "LEFT",
    13: "RIGHT",
    14: "UP_LEFT",
    15: "UP_RIGHT",
    16: "WANT_UP",
    17: "WANT_DOWN",
    18: "WANT_DOWN_SLOW",
    19: "WANT_UP_SLOW",
    20: "SPRINTING",
    21: "ASCEND_BLOCK",
    22: "DESCEND_BLOCK",
    23: "SNEAK_TOGGLE_DOWN",
    24: "PERSIST_SNEAK",
    25: "START_SPRINTING",
    26: "STOP_SPRINTING",
    27: "START_SNEAKING",
    28: "STOP_SNEAKING",
    29: "START_SWIMMING",
    30: "STOP_SWIMMING",
    31: "START_JUMPING",
    32: "START_GLIDING",
    33: "STOP_GLIDING",
    34: "PERFORM_ITEM_INTERACTION",
    35: "PERFORM_BLOCK_ACTIONS",
    36: "PERFORM_ITEM_STACK_REQUEST",
    37: "HANDLED_TELEPORT",
    38: "EMOTING",
    39: "MISSED_SWING",
    40: "START_CRAWLING",
    41: "STOP_CRAWLING",
    42: "START_FLYING",
    43: "STOP_FLYING",
    44: "ACK_ACTOR_DATA",
    45: "IN_CLIENT_PREDICTED_VEHICLE",
    46: "PADDLING_LEFT",
    47: "PADDLING_RIGHT",
    48: "BLOCK_BREAKING_DELAY_ENABLED",
    49: "HORIZONTAL_COLLISION",
    50: "VERTICAL_COLLISION",
    51: "DOWN_LEFT",
    52: "DOWN_RIGHT",
    53: "START_USING_ITEM",
    54: "IS_CAMERA_RELATIVE_MOVEMENT_ENABLED",
    55: "IS_ROT_CONTROLLED_BY_MOVE_DIRECTION",
    56: "START_SPIN_ATTACK",
    57: "STOP_SPIN_ATTACK",
    58: "IS_HOTBAR_ONLY_TOUCH",
    59: "JUMP_RELEASED_RAW",
    60: "JUMP_PRESSED_RAW",
    61: "JUMP_CURRENT_RAW",
    62: "SNEAK_RELEASED_RAW",
    63: "SNEAK_PRESSED_RAW",
    64: "SNEAK_CURRENT_RAW",
}


def decode_input_flags(flags):
    return [name for bit, name in sorted(INPUT_FLAG_NAMES.items()) if (flags >> bit) & 1]