# ---------------------------------------------------------------- Bedrock packet id -> name
# Mirrors pmmp/BedrockProtocol ProtocolInfo (1.21.50 / protocol 766) so unknown or
# informational packets can be logged by name instead of a bare number.

PACKET_NAMES = {
1: "LOGIN_PACKET", 2: "PLAY_STATUS_PACKET", 3: "SERVER_TO_CLIENT_HANDSHAKE_PACKET", 4:
    "CLIENT_TO_SERVER_HANDSHAKE_PACKET", 5: "DISCONNECT_PACKET", 6: "RESOURCE_PACKS_INFO_PACKET", 7:
    "RESOURCE_PACK_STACK_PACKET", 8: "RESOURCE_PACK_CLIENT_RESPONSE_PACKET", 9: "TEXT_PACKET", 10:
    "SET_TIME_PACKET", 11: "START_GAME_PACKET", 12: "ADD_PLAYER_PACKET", 13: "ADD_ACTOR_PACKET", 14:
    "REMOVE_ACTOR_PACKET", 15: "ADD_ITEM_ACTOR_PACKET", 16:
    "SERVER_PLAYER_POST_MOVE_POSITION_PACKET", 17: "TAKE_ITEM_ACTOR_PACKET", 18:
    "MOVE_ACTOR_ABSOLUTE_PACKET", 19: "MOVE_PLAYER_PACKET", 21: "UPDATE_BLOCK_PACKET", 22:
    "ADD_PAINTING_PACKET", 25: "LEVEL_EVENT_PACKET", 26: "BLOCK_EVENT_PACKET", 27:
    "ACTOR_EVENT_PACKET", 28: "MOB_EFFECT_PACKET", 29: "UPDATE_ATTRIBUTES_PACKET", 30:
    "INVENTORY_TRANSACTION_PACKET", 31: "MOB_EQUIPMENT_PACKET", 32: "MOB_ARMOR_EQUIPMENT_PACKET",
    33: "INTERACT_PACKET", 34: "BLOCK_PICK_REQUEST_PACKET", 35: "ACTOR_PICK_REQUEST_PACKET", 36:
    "PLAYER_ACTION_PACKET", 38: "HURT_ARMOR_PACKET", 39: "SET_ACTOR_DATA_PACKET", 40:
    "SET_ACTOR_MOTION_PACKET", 41: "SET_ACTOR_LINK_PACKET", 42: "SET_HEALTH_PACKET", 43:
    "SET_SPAWN_POSITION_PACKET", 44: "ANIMATE_PACKET", 45: "RESPAWN_PACKET", 46:
    "CONTAINER_OPEN_PACKET", 47: "CONTAINER_CLOSE_PACKET", 48: "PLAYER_HOTBAR_PACKET", 49:
    "INVENTORY_CONTENT_PACKET", 50: "INVENTORY_SLOT_PACKET", 51: "CONTAINER_SET_DATA_PACKET", 52:
    "CRAFTING_DATA_PACKET", 54: "GUI_DATA_PICK_ITEM_PACKET", 56: "BLOCK_ACTOR_DATA_PACKET", 58:
    "LEVEL_CHUNK_PACKET", 59: "SET_COMMANDS_ENABLED_PACKET", 60: "SET_DIFFICULTY_PACKET", 61:
    "CHANGE_DIMENSION_PACKET", 62: "SET_PLAYER_GAME_TYPE_PACKET", 63: "PLAYER_LIST_PACKET", 64:
    "SIMPLE_EVENT_PACKET", 65: "LEGACY_TELEMETRY_EVENT_PACKET", 66: "SPAWN_EXPERIENCE_ORB_PACKET",
    67: "CLIENTBOUND_MAP_ITEM_DATA_PACKET", 68: "MAP_INFO_REQUEST_PACKET", 69:
    "REQUEST_CHUNK_RADIUS_PACKET", 70: "CHUNK_RADIUS_UPDATED_PACKET", 72:
    "GAME_RULES_CHANGED_PACKET", 73: "CAMERA_PACKET", 74: "BOSS_EVENT_PACKET", 75:
    "SHOW_CREDITS_PACKET", 76: "AVAILABLE_COMMANDS_PACKET", 77: "COMMAND_REQUEST_PACKET", 78:
    "COMMAND_BLOCK_UPDATE_PACKET", 79: "COMMAND_OUTPUT_PACKET", 80: "UPDATE_TRADE_PACKET", 81:
    "UPDATE_EQUIP_PACKET", 82: "RESOURCE_PACK_DATA_INFO_PACKET", 83:
    "RESOURCE_PACK_CHUNK_DATA_PACKET", 84: "RESOURCE_PACK_CHUNK_REQUEST_PACKET", 85:
    "TRANSFER_PACKET", 86: "PLAY_SOUND_PACKET", 87: "STOP_SOUND_PACKET", 88: "SET_TITLE_PACKET", 89:
    "ADD_BEHAVIOR_TREE_PACKET", 90: "STRUCTURE_BLOCK_UPDATE_PACKET", 91: "SHOW_STORE_OFFER_PACKET",
    92: "PURCHASE_RECEIPT_PACKET", 93: "PLAYER_SKIN_PACKET", 94: "SUB_CLIENT_LOGIN_PACKET", 95:
    "AUTOMATION_CLIENT_CONNECT_PACKET", 96: "SET_LAST_HURT_BY_PACKET", 97: "BOOK_EDIT_PACKET", 98:
    "NPC_REQUEST_PACKET", 99: "PHOTO_TRANSFER_PACKET", 100: "MODAL_FORM_REQUEST_PACKET", 101:
    "MODAL_FORM_RESPONSE_PACKET", 102: "SERVER_SETTINGS_REQUEST_PACKET", 103:
    "SERVER_SETTINGS_RESPONSE_PACKET", 104: "SHOW_PROFILE_PACKET", 105:
    "SET_DEFAULT_GAME_TYPE_PACKET", 106: "REMOVE_OBJECTIVE_PACKET", 107:
    "SET_DISPLAY_OBJECTIVE_PACKET", 108: "SET_SCORE_PACKET", 109: "LAB_TABLE_PACKET", 110:
    "UPDATE_BLOCK_SYNCED_PACKET", 111: "MOVE_ACTOR_DELTA_PACKET", 112:
    "SET_SCOREBOARD_IDENTITY_PACKET", 113: "SET_LOCAL_PLAYER_AS_INITIALIZED_PACKET", 114:
    "UPDATE_SOFT_ENUM_PACKET", 115: "NETWORK_STACK_LATENCY_PACKET", 118:
    "SPAWN_PARTICLE_EFFECT_PACKET", 119: "AVAILABLE_ACTOR_IDENTIFIERS_PACKET", 121:
    "NETWORK_CHUNK_PUBLISHER_UPDATE_PACKET", 122: "BIOME_DEFINITION_LIST_PACKET", 123:
    "LEVEL_SOUND_EVENT_PACKET", 124: "LEVEL_EVENT_GENERIC_PACKET", 125: "LECTERN_UPDATE_PACKET",
    129: "CLIENT_CACHE_STATUS_PACKET", 130: "ON_SCREEN_TEXTURE_ANIMATION_PACKET", 131:
    "MAP_CREATE_LOCKED_COPY_PACKET", 132: "STRUCTURE_TEMPLATE_DATA_REQUEST_PACKET", 133:
    "STRUCTURE_TEMPLATE_DATA_RESPONSE_PACKET", 135: "CLIENT_CACHE_BLOB_STATUS_PACKET", 136:
    "CLIENT_CACHE_MISS_RESPONSE_PACKET", 137: "EDUCATION_SETTINGS_PACKET", 138: "EMOTE_PACKET", 139:
    "MULTIPLAYER_SETTINGS_PACKET", 140: "SETTINGS_COMMAND_PACKET", 141: "ANVIL_DAMAGE_PACKET", 142:
    "COMPLETED_USING_ITEM_PACKET", 143: "NETWORK_SETTINGS_PACKET", 144: "PLAYER_AUTH_INPUT_PACKET",
    145: "CREATIVE_CONTENT_PACKET", 146: "PLAYER_ENCHANT_OPTIONS_PACKET", 147:
    "ITEM_STACK_REQUEST_PACKET", 148: "ITEM_STACK_RESPONSE_PACKET", 149:
    "PLAYER_ARMOR_DAMAGE_PACKET", 150: "CODE_BUILDER_PACKET", 151: "UPDATE_PLAYER_GAME_TYPE_PACKET",
    152: "EMOTE_LIST_PACKET", 153: "POSITION_TRACKING_DB_SERVER_BROADCAST_PACKET", 154:
    "POSITION_TRACKING_DB_CLIENT_REQUEST_PACKET", 155: "DEBUG_INFO_PACKET", 156:
    "PACKET_VIOLATION_WARNING_PACKET", 157: "MOTION_PREDICTION_HINTS_PACKET", 158:
    "ANIMATE_ENTITY_PACKET", 159: "CAMERA_SHAKE_PACKET", 160: "PLAYER_FOG_PACKET", 161:
    "CORRECT_PLAYER_MOVE_PREDICTION_PACKET", 162: "ITEM_REGISTRY_PACKET", 164:
    "CLIENTBOUND_DEBUG_RENDERER_PACKET", 165: "SYNC_ACTOR_PROPERTY_PACKET", 166:
    "ADD_VOLUME_ENTITY_PACKET", 167: "REMOVE_VOLUME_ENTITY_PACKET", 168: "SIMULATION_TYPE_PACKET",
    169: "NPC_DIALOGUE_PACKET", 170: "EDU_URI_RESOURCE_PACKET", 171: "CREATE_PHOTO_PACKET", 172:
    "UPDATE_SUB_CHUNK_BLOCKS_PACKET", 174: "SUB_CHUNK_PACKET", 175: "SUB_CHUNK_REQUEST_PACKET", 176:
    "PLAYER_START_ITEM_COOLDOWN_PACKET", 177: "SCRIPT_MESSAGE_PACKET", 178:
    "CODE_BUILDER_SOURCE_PACKET", 179: "TICKING_AREAS_LOAD_STATUS_PACKET", 180:
    "DIMENSION_DATA_PACKET", 181: "AGENT_ACTION_EVENT_PACKET", 182: "CHANGE_MOB_PROPERTY_PACKET",
    183: "LESSON_PROGRESS_PACKET", 184: "REQUEST_ABILITY_PACKET", 185: "REQUEST_PERMISSIONS_PACKET",
    186: "TOAST_REQUEST_PACKET", 187: "UPDATE_ABILITIES_PACKET", 188:
    "UPDATE_ADVENTURE_SETTINGS_PACKET", 189: "DEATH_INFO_PACKET", 190: "EDITOR_NETWORK_PACKET", 191:
    "FEATURE_REGISTRY_PACKET", 192: "SERVER_STATS_PACKET", 193: "REQUEST_NETWORK_SETTINGS_PACKET",
    194: "GAME_TEST_REQUEST_PACKET", 195: "GAME_TEST_RESULTS_PACKET", 196:
    "UPDATE_CLIENT_INPUT_LOCKS_PACKET", 198: "CAMERA_PRESETS_PACKET", 199:
    "UNLOCKED_RECIPES_PACKET", 300: "CAMERA_INSTRUCTION_PACKET", 302: "TRIM_DATA_PACKET", 303:
    "OPEN_SIGN_PACKET", 304: "AGENT_ANIMATION_PACKET", 305: "REFRESH_ENTITLEMENTS_PACKET", 306:
    "PLAYER_TOGGLE_CRAFTER_SLOT_REQUEST_PACKET", 307: "SET_PLAYER_INVENTORY_OPTIONS_PACKET", 308:
    "SET_HUD_PACKET", 309: "AWARD_ACHIEVEMENT_PACKET", 310: "CLIENTBOUND_CLOSE_FORM_PACKET", 312:
    "SERVERBOUND_LOADING_SCREEN_PACKET", 313: "JIGSAW_STRUCTURE_DATA_PACKET", 314:
    "CURRENT_STRUCTURE_FEATURE_PACKET", 315: "SERVERBOUND_DIAGNOSTICS_PACKET", 316:
    "CAMERA_AIM_ASSIST_PACKET", 317: "CONTAINER_REGISTRY_CLEANUP_PACKET", 318:
    "MOVEMENT_EFFECT_PACKET", 320: "CAMERA_AIM_ASSIST_PRESETS_PACKET", 321:
    "CLIENT_CAMERA_AIM_ASSIST_PACKET", 322: "CLIENT_MOVEMENT_PREDICTION_SYNC_PACKET", 323:
    "UPDATE_CLIENT_OPTIONS_PACKET", 324: "PLAYER_VIDEO_CAPTURE_PACKET", 325:
    "PLAYER_UPDATE_ENTITY_OVERRIDES_PACKET", 326: "PLAYER_LOCATION_PACKET", 327:
    "CLIENTBOUND_CONTROL_SCHEME_SET_PACKET", 328: "PRIMITIVE_SHAPES_PACKET", 329:
    "SERVERBOUND_PACK_SETTING_CHANGE_PACKET", 330: "CLIENTBOUND_DATA_STORE_PACKET", 331:
    "GRAPHICS_OVERRIDE_PARAMETER_PACKET", 332: "SERVERBOUND_DATA_STORE_PACKET", 333:
    "CLIENTBOUND_DATA_DRIVEN_UI_SHOW_SCREEN_PACKET", 334:
    "CLIENTBOUND_DATA_DRIVEN_UI_CLOSE_SCREEN_PACKET", 335:
    "CLIENTBOUND_DATA_DRIVEN_UI_RELOAD_PACKET", 336: "CLIENTBOUND_TEXTURE_SHIFT_PACKET", 337:
    "VOXEL_SHAPES_PACKET", 338: "CAMERA_SPLINE_PACKET", 339:
    "CAMERA_AIM_ASSIST_ACTOR_PRIORITY_PACKET", 340: "RESOURCE_PACKS_READY_FOR_VALIDATION_PACKET",
    341: "LOCATOR_BAR_PACKET", 342: "PARTY_CHANGED_PACKET", 343:
    "SERVERBOUND_DATA_DRIVEN_SCREEN_CLOSED_PACKET", 344: "SYNC_WORLD_CLOCKS_PACKET", 345:
    "CLIENTBOUND_ATTRIBUTE_LAYER_SYNC_PACKET", 346: "SERVER_STORE_INFO_PACKET", 347:
    "SERVER_PRESENCE_INFO_PACKET", 348: "CLIENTBOUND_UPDATE_SOUND_DATA_PACKET", 349:
    "SEND_PARTY_DESTINATION_COOKIE_PACKET", 350: "PARTY_DESTINATION_COOKIE_RESPONSE_PACKET"
}

def packet_name(pid):
    return PACKET_NAMES.get(pid, "UNKNOWN_%d" % pid)
