# ---------------------------------------------------------------- Bedrock packet ids (protocol 766)
"""Minecraft Bedrock packet identifiers for protocol 766 (v1.21.50)."""

PID_LOGIN = 1
PID_PLAY_STATUS = 2
PID_S2C_HANDSHAKE = 3
PID_C2S_HANDSHAKE = 4
PID_DISCONNECT = 5
PID_PACKS_INFO = 6
PID_PACK_STACK = 7
PID_PACK_RESPONSE = 8
PID_TEXT = 9
PID_SET_TIME = 10
PID_START_GAME = 11
PID_ADD_PLAYER = 12
PID_ADD_ACTOR = 13
PID_REMOVE_ACTOR = 14
PID_ADD_ITEM_ACTOR = 15
PID_TAKE_ITEM_ACTOR = 17
PID_MOVE_ACTOR_ABSOLUTE = 18
PID_MOVE_PLAYER = 19
PID_UPDATE_BLOCK = 21
PID_LEVEL_EVENT = 25
PID_ACTOR_EVENT = 27
PID_UPDATE_ATTRIBUTES = 29
PID_INVENTORY_TRANSACTION = 30
PID_MOB_EQUIPMENT = 31
PID_INTERACT = 33
PID_PLAYER_ACTION = 36
PID_SET_ACTOR_DATA = 39
PID_SET_ACTOR_MOTION = 40
PID_ANIMATE = 44
PID_CONTAINER_OPEN = 46
PID_CONTAINER_CLOSE = 47
PID_PLAYER_HOTBAR = 48
PID_INVENTORY_CONTENT = 49
PID_INVENTORY_SLOT = 50
PID_CRAFTING_DATA = 52
PID_CHUNK = 58
PID_PLAYER_LIST = 63
PID_REQ_RADIUS = 69
PID_RADIUS_UPDATED = 70
PID_PLAY_SOUND = 86
PID_INITIALIZED = 113
PID_ACTOR_IDS = 119
PID_PUBLISHER = 121
PID_BIOME_DEFS = 122
PID_LEVEL_SOUND_EVENT = 123
PID_CACHE_STATUS = 129
PID_NETWORK_SETTINGS = 143
PID_AUTH_INPUT = 144
PID_CREATIVE = 145
PID_ITEM_STACK_REQUEST = 147
PID_ITEM_STACK_RESPONSE = 148
PID_UPDATE_ABILITIES = 187
PID_UPDATE_ADVENTURE_SETTINGS = 188
PID_REQUEST_NETWORK_SETTINGS = 193

# PlayStatus packet status codes
PLAY_LOGIN_SUCCESS = 0
PLAY_FAILED_CLIENT = 1
PLAY_FAILED_SERVER = 2

# InteractPacket actions (protocol 766)
INTERACT_LEAVE_VEHICLE = 3
INTERACT_MOUSEOVER = 4
INTERACT_OPEN_NPC = 5
INTERACT_OPEN_INVENTORY = 6

# LevelSoundEvent ids (numeric in protocol 766)
SOUND_HIT = 1

# LevelEvent ids used for block break crack animation
LEVEL_EVENT_BLOCK_START_BREAK = 3600
LEVEL_EVENT_BLOCK_STOP_BREAK = 3601
LEVEL_EVENT_BLOCK_BREAK_SPEED = 3602